services:

  synapse:
    container_name: synapse
    image: matrixdotorg/synapse:latest
    restart: on-failure
    volumes:
      - ./data/synapse:/data
    ports:
      - 8008:8008
      - 8448:8448
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8008" ]
      interval: 1s
      timeout: 10s
      retries: 10

  element:
    container_name: element
    image: vectorim/element-web:latest
    restart: on-failure
    volumes:
      - ./data/element/config.json:/app/config.json
    ports:
      - 8080:80
    depends_on:
      synapse:
        condition: service_healthy

  telegram:
    container_name: telegram
    image: dock.mau.dev/tulir/mautrix-telegram:latest
    restart: on-failure
    volumes:
      - ./data/telegram:/data
    ports:
      - 29317:29317
    depends_on:
      synapse:
        condition: service_healthy

  whatsapp:
    container_name: whatsapp
    image: dock.mau.dev/tulir/mautrix-whatsapp:latest
    restart: on-failure
    volumes:
      - ./data/whatsapp:/data
    ports:
      - 29318:29318
    depends_on:
      synapse:
        condition: service_healthy
