version: "3.9"

services:

  synapse:
    container_name: synapse
    image: matrixdotorg/synapse:latest
    restart: on-failure
    volumes:
      - ./data/synapse:/data
    ports:
      - 8008:8008
      - 8448:8448
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8008" ]
      interval: 10s
      timeout: 10s
      retries: 10

  element:
    container_name: element
    image: vectorim/element-web:latest
    restart: on-failure
    volumes:
      - ./data/element/config.json:/app/config.json
    ports:
      - 8080:80
    depends_on:
      synapse:
        condition: service_healthy

  telegram:
    container_name: telegram
    image: dock.mau.dev/tulir/mautrix-telegram:latest
    restart: on-failure
    volumes:
      - ./data/telegram:/data
    ports:
      - 29317:29317
    depends_on:
      synapse:
        condition: service_healthy

  whatsapp:
    container_name: whatsapp
    image: dock.mau.dev/tulir/mautrix-whatsapp:latest
    restart: on-failure
    volumes:
      - ./data/whatsapp:/data
    ports:
      - 29318:29318
    depends_on:
      synapse:
        condition: service_healthy

  signal:
    container_name: signal
    image: dock.mau.dev/tulir/mautrix-signal
    restart: on-failure
    volumes:
      - ./data/signal:/data
      - ./data/signal:/signald
    depends_on:
      synapse:
        condition: service_healthy
      signal_db:
        condition: service_healthy

  signald:
    container_name: signald
    image: docker.io/finn/signald
    restart: on-failure
    volumes:
      - ./data/signal:/signald

  signal_db:
    container_name: signal-db
    image: postgres:13-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: mautrixsignal
      POSTGRES_DATABASE: mautrixsignal
      POSTGRES_PASSWORD: foobar
    volumes:
      - ./data/signal/db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U mautrixsignal" ]
      interval: 10s
      timeout: 10s
      retries: 10